// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetCore.Infrastructure.Data;

#nullable disable

namespace PetCore.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409002537_MigracaoCompleta")]
    partial class MigracaoCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetCore.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime>("DataHoraAgendada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataHoraAgendada");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracaoMinutos");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizadoEm");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciadoEm");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivoCancelamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacienteId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("VeterinarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarioId");

                    b.HasKey("Id")
                        .HasName("pK_agendamentos");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("iX_agendamentos_pacienteId");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("iX_agendamentos_veterinarioId");

                    b.HasIndex("ClinicaId", "DataHoraAgendada")
                        .HasDatabaseName("iX_agendamentos_clinicaId_dataHoraAgendada");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CategoriaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pK_categoriasFinanceiras");

                    b.ToTable("categoriasFinanceiras");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<string>("Cor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pK_categoriasProduto");

                    b.ToTable("categoriasProduto");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CentroCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pK_centrosCusto");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("iX_centrosCusto_clinicaId");

                    b.ToTable("centrosCusto");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logoUrl");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nomeFantasia");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razaoSocial");

                    b.Property<string>("Rua")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pK_clinicas");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("iX_clinicas_cnpj")
                        .HasFilter("\"cnpj\" IS NOT NULL");

                    b.ToTable("clinicas");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ClinicaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("perfil");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id")
                        .HasName("pK_clinicaUsuarios");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("iX_clinicaUsuarios_usuarioId");

                    b.HasIndex("ClinicaId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("iX_clinicaUsuarios_clinicaId_usuarioId");

                    b.ToTable("clinicaUsuarios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pK_especies");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("iX_especies_nome");

                    b.ToTable("especies");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Evolucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alimentacao")
                        .HasColumnType("text")
                        .HasColumnName("alimentacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("integer")
                        .HasColumnName("frequenciaCardiaca");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("integer")
                        .HasColumnName("frequenciaRespiratoria");

                    b.Property<Guid>("InternacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("internacaoId");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("text")
                        .HasColumnName("medicamentos");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("peso");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperatura");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarioId");

                    b.HasKey("Id")
                        .HasName("pK_evolucoes");

                    b.HasIndex("InternacaoId")
                        .HasDatabaseName("iX_evolucoes_internacaoId");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("iX_evolucoes_veterinarioId");

                    b.ToTable("evolucoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Internacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<string>("Baia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("baia");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime?>("DataAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataAlta");

                    b.Property<DateTime>("DataInternacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataInternacao");

                    b.Property<string>("Dieta")
                        .HasColumnType("text")
                        .HasColumnName("dieta");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("ObservacoesAlta")
                        .HasColumnType("text")
                        .HasColumnName("observacoesAlta");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacienteId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarioId");

                    b.HasKey("Id")
                        .HasName("pK_internacoes");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("iX_internacoes_pacienteId");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("iX_internacoes_veterinarioId");

                    b.ToTable("internacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedidoId");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoId");

                    b.Property<int?>("QuantidadeAprovada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidadeAprovada");

                    b.Property<int>("QuantidadeRecebida")
                        .HasColumnType("integer")
                        .HasColumnName("quantidadeRecebida");

                    b.Property<int>("QuantidadeSolicitada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidadeSolicitada");

                    b.HasKey("Id")
                        .HasName("pK_itensPedido");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("iX_itensPedido_pedidoId");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("iX_itensPedido_produtoId");

                    b.ToTable("itensPedido");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enderecoIp");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidadeId");

                    b.Property<string>("NovoValor")
                        .HasColumnType("text")
                        .HasColumnName("novoValor");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioId");

                    b.Property<string>("ValorAntigo")
                        .HasColumnType("text")
                        .HasColumnName("valorAntigo");

                    b.HasKey("Id")
                        .HasName("pK_logsAuditoria");

                    b.HasIndex("Entidade")
                        .HasDatabaseName("iX_logsAuditoria_entidade");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("iX_logsAuditoria_usuarioId");

                    b.HasIndex("ClinicaId", "CriadoEm")
                        .HasDatabaseName("iX_logsAuditoria_clinicaId_criadoEm");

                    b.ToTable("logsAuditoria");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovadoPorId");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criadoPorId");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataAprovacao");

                    b.Property<int>("EstoqueAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("estoqueAnterior");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<int>("NovoEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("novoEstoque");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedidoId");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produtoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pK_movimentacoes");

                    b.HasIndex("AprovadoPorId")
                        .HasDatabaseName("iX_movimentacoes_aprovadoPorId");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("iX_movimentacoes_criadoPorId");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("iX_movimentacoes_pedidoId");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("iX_movimentacoes_produtoId");

                    b.ToTable("movimentacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alergias")
                        .HasColumnType("text")
                        .HasColumnName("alergias");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<bool>("Castrado")
                        .HasColumnType("boolean")
                        .HasColumnName("castrado");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<string>("Cor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataNascimento");

                    b.Property<DateTime?>("DataObito")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataObito");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid")
                        .HasColumnName("especieId");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("fotoUrl");

                    b.Property<string>("Microchip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("Obito")
                        .HasColumnType("boolean")
                        .HasColumnName("obito");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("peso");

                    b.Property<Guid?>("RacaId")
                        .HasColumnType("uuid")
                        .HasColumnName("racaId");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorId");

                    b.HasKey("Id")
                        .HasName("pK_pacientes");

                    b.HasIndex("EspecieId")
                        .HasDatabaseName("iX_pacientes_especieId");

                    b.HasIndex("RacaId")
                        .HasDatabaseName("iX_pacientes_racaId");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("iX_pacientes_tutorId");

                    b.HasIndex("ClinicaId", "Nome")
                        .HasDatabaseName("iX_pacientes_clinicaId_nome");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ParcelaTransacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataPagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataVencimento");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numeroParcela");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("transacaoId");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pK_parcelasTransacao");

                    b.HasIndex("TransacaoId")
                        .HasDatabaseName("iX_parcelasTransacao_transacaoId");

                    b.ToTable("parcelasTransacao");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovadoPorId");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criadoPorId");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataAprovacao");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text")
                        .HasColumnName("justificativa");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Periodo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("periodo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pK_pedidos");

                    b.HasIndex("AprovadoPorId")
                        .HasDatabaseName("iX_pedidos_aprovadoPorId");

                    b.HasIndex("ClinicaId")
                        .HasDatabaseName("iX_pedidos_clinicaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("iX_pedidos_codigo");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("iX_pedidos_criadoPorId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prescricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Dosagem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosagem");

                    b.Property<string>("Duracao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("duracao");

                    b.Property<string>("Frequencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequencia");

                    b.Property<string>("Instrucoes")
                        .HasColumnType("text")
                        .HasColumnName("instrucoes");

                    b.Property<string>("NomeMedicamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nomeMedicamento");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("prontuarioId");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("ViaAdministracao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("viaAdministracao");

                    b.HasKey("Id")
                        .HasName("pK_prescricoes");

                    b.HasIndex("ProntuarioId")
                        .HasDatabaseName("iX_prescricoes_prontuarioId");

                    b.ToTable("prescricoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apresentacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("apresentacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoriaId");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigoBarras");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataValidade");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("integer")
                        .HasColumnName("estoqueAtual");

                    b.Property<int?>("EstoqueMaximo")
                        .HasColumnType("integer")
                        .HasColumnName("estoqueMaximo");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoqueMinimo");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("PrecoCusto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precoCusto");

                    b.Property<decimal?>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precoVenda");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidadeId");

                    b.HasKey("Id")
                        .HasName("pK_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("iX_produtos_categoriaId");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("iX_produtos_unidadeId");

                    b.HasIndex("ClinicaId", "CodigoBarras")
                        .IsUnique()
                        .HasDatabaseName("iX_produtos_clinicaId_codigoBarras")
                        .HasFilter("\"codigoBarras\" IS NOT NULL");

                    b.HasIndex("ClinicaId", "Nome")
                        .HasDatabaseName("iX_produtos_clinicaId_nome");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamentoId");

                    b.Property<string>("Anamnese")
                        .HasColumnType("text")
                        .HasColumnName("anamnese");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<string>("DiagnosticoDiferencial")
                        .HasColumnType("text")
                        .HasColumnName("diagnosticoDiferencial");

                    b.Property<string>("ExameFisico")
                        .HasColumnType("text")
                        .HasColumnName("exameFisico");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("integer")
                        .HasColumnName("frequenciaCardiaca");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("integer")
                        .HasColumnName("frequenciaRespiratoria");

                    b.Property<string>("Hidratacao")
                        .HasColumnType("text")
                        .HasColumnName("hidratacao");

                    b.Property<string>("Historico")
                        .HasColumnType("text")
                        .HasColumnName("historico");

                    b.Property<string>("Linfonodos")
                        .HasColumnType("text")
                        .HasColumnName("linfonodos");

                    b.Property<string>("Mucosas")
                        .HasColumnType("text")
                        .HasColumnName("mucosas");

                    b.Property<string>("NotasInternas")
                        .HasColumnType("text")
                        .HasColumnName("notasInternas");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacienteId");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("peso");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("queixaPrincipal");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperatura");

                    b.Property<string>("Tratamento")
                        .HasColumnType("text")
                        .HasColumnName("tratamento");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarioId");

                    b.HasKey("Id")
                        .HasName("pK_prontuarios");

                    b.HasIndex("AgendamentoId")
                        .IsUnique()
                        .HasDatabaseName("iX_prontuarios_agendamentoId");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("iX_prontuarios_pacienteId");

                    b.HasIndex("VeterinarioId")
                        .HasDatabaseName("iX_prontuarios_veterinarioId");

                    b.HasIndex("ClinicaId", "CriadoEm")
                        .HasDatabaseName("iX_prontuarios_clinicaId_criadoEm");

                    b.ToTable("prontuarios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid")
                        .HasColumnName("especieId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pK_racas");

                    b.HasIndex("EspecieId")
                        .HasDatabaseName("iX_racas_especieId");

                    b.ToTable("racas");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ResultadoExame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoResultadoUrl")
                        .HasColumnType("text")
                        .HasColumnName("arquivoResultadoUrl");

                    b.Property<string>("Conclusao")
                        .HasColumnType("text")
                        .HasColumnName("conclusao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("RealizadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("realizadoPorId");

                    b.Property<Guid>("SolicitacaoExameId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacaoExameId");

                    b.Property<string>("TextoResultado")
                        .HasColumnType("text")
                        .HasColumnName("textoResultado");

                    b.Property<string>("ValoresReferencia")
                        .HasColumnType("text")
                        .HasColumnName("valoresReferencia");

                    b.HasKey("Id")
                        .HasName("pK_resultadosExame");

                    b.HasIndex("RealizadoPorId")
                        .HasDatabaseName("iX_resultadosExame_realizadoPorId");

                    b.HasIndex("SolicitacaoExameId")
                        .IsUnique()
                        .HasDatabaseName("iX_resultadosExame_solicitacaoExameId");

                    b.ToTable("resultadosExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataColeta");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataConclusao");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataSolicitacao");

                    b.Property<string>("IndicacaoClinica")
                        .HasColumnType("text")
                        .HasColumnName("indicacaoClinica");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacienteId");

                    b.Property<Guid?>("ProntuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("prontuarioId");

                    b.Property<Guid>("SolicitadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitadoPorId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TipoExameId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipoExameId");

                    b.HasKey("Id")
                        .HasName("pK_solicitacoesExame");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("iX_solicitacoesExame_pacienteId");

                    b.HasIndex("ProntuarioId")
                        .HasDatabaseName("iX_solicitacoesExame_prontuarioId");

                    b.HasIndex("SolicitadoPorId")
                        .HasDatabaseName("iX_solicitacoesExame_solicitadoPorId");

                    b.HasIndex("TipoExameId")
                        .HasDatabaseName("iX_solicitacoesExame_tipoExameId");

                    b.ToTable("solicitacoesExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TipoExame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal?>("PrecoDefault")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precoDefault");

                    b.HasKey("Id")
                        .HasName("pK_tiposExame");

                    b.ToTable("tiposExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TokenAtualizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiraEm");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogadoEm");

                    b.Property<string>("SubstituidoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("substituidoPor");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id")
                        .HasName("pK_tokensAtualizacao");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("iX_tokensAtualizacao_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("iX_tokensAtualizacao_usuarioId");

                    b.ToTable("tokensAtualizacao");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TransacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamentoId");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<Guid>("CategoriaFinanceiraId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoriaFinanceiraId");

                    b.Property<Guid?>("CentroCustoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centroCustoId");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("criadoPorId");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataPagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataVencimento");

                    b.Property<decimal?>("Desconto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("InternacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("internacaoId");

                    b.Property<string>("MetodoPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("metodoPagamento");

                    b.Property<string>("NumeroNota")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeroNota");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid?>("SolicitacaoExameId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacaoExameId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorId");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valorPago");

                    b.HasKey("Id")
                        .HasName("pK_transacoesFinanceiras");

                    b.HasIndex("AgendamentoId")
                        .HasDatabaseName("iX_transacoesFinanceiras_agendamentoId");

                    b.HasIndex("CategoriaFinanceiraId")
                        .HasDatabaseName("iX_transacoesFinanceiras_categoriaFinanceiraId");

                    b.HasIndex("CentroCustoId")
                        .HasDatabaseName("iX_transacoesFinanceiras_centroCustoId");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("iX_transacoesFinanceiras_criadoPorId");

                    b.HasIndex("InternacaoId")
                        .HasDatabaseName("iX_transacoesFinanceiras_internacaoId");

                    b.HasIndex("SolicitacaoExameId")
                        .HasDatabaseName("iX_transacoesFinanceiras_solicitacaoExameId");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("iX_transacoesFinanceiras_tutorId");

                    b.HasIndex("ClinicaId", "DataVencimento")
                        .HasDatabaseName("iX_transacoesFinanceiras_clinicaId_dataVencimento");

                    b.HasIndex("ClinicaId", "Status")
                        .HasDatabaseName("iX_transacoesFinanceiras_clinicaId_status");

                    b.ToTable("transacoesFinanceiras");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinicaId");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Rua")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("TelefoneSecundario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefoneSecundario");

                    b.HasKey("Id")
                        .HasName("pK_tutores");

                    b.HasIndex("ClinicaId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("iX_tutores_clinicaId_cpf")
                        .HasFilter("\"cpf\" IS NOT NULL");

                    b.HasIndex("ClinicaId", "Email")
                        .IsUnique()
                        .HasDatabaseName("iX_tutores_clinicaId_email")
                        .HasFilter("\"email\" IS NOT NULL");

                    b.ToTable("tutores");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.UnidadeProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pK_unidadesProduto");

                    b.ToTable("unidadesProduto");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizadoEm");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criadoEm");

                    b.Property<string>("Crmv")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crmv");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senhaHash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pK_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("iX_usuarios_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "Veterinario")
                        .WithMany("AgendamentosComoVet")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clinica");

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CentroCusto", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("CentrosCusto")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ClinicaUsuario", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("ClinicaUsuarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ClinicaUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Evolucao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Internacao", "Internacao")
                        .WithMany("Evolucoes")
                        .HasForeignKey("InternacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Internacao");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Internacao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Internacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ItemPedido", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Usuario", "AprovadoPor")
                        .WithMany("MovimentacoesAprovadas")
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany("MovimentacoesCriadas")
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("CriadoPor");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pacientes")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Especie");

                    b.Navigation("Raca");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ParcelaTransacao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.TransacaoFinanceira", "Transacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Usuario", "AprovadoPor")
                        .WithMany("PedidosAprovados")
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany("PedidosCriados")
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("Clinica");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prescricao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Prescricoes")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Produto", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.CategoriaProduto", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Produtos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.UnidadeProduto", "Unidade")
                        .WithMany("Produtos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Clinica");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Agendamento", "Agendamento")
                        .WithOne("Prontuario")
                        .HasForeignKey("PetCore.Domain.Entities.Prontuario", "AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Prontuarios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "Veterinario")
                        .WithMany("Prontuarios")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Raca", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.ResultadoExame", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Usuario", "RealizadoPor")
                        .WithMany()
                        .HasForeignKey("RealizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithOne("Resultado")
                        .HasForeignKey("PetCore.Domain.Entities.ResultadoExame", "SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealizadoPor");

                    b.Navigation("SolicitacaoExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Paciente", "Paciente")
                        .WithMany("SolicitacoesExame")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("SolicitacoesExame")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Usuario", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.TipoExame", "TipoExame")
                        .WithMany()
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("SolicitadoPor");

                    b.Navigation("TipoExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TokenAtualizacao", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TransacaoFinanceira", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.CategoriaFinanceira", "CategoriaFinanceira")
                        .WithMany()
                        .HasForeignKey("CategoriaFinanceiraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.CentroCusto", "CentroCusto")
                        .WithMany("Transacoes")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Transacoes")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Internacao", "Internacao")
                        .WithMany("Transacoes")
                        .HasForeignKey("InternacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.SolicitacaoExame", "SolicitacaoExame")
                        .WithMany("Transacoes")
                        .HasForeignKey("SolicitacaoExameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCore.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Transacoes")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agendamento");

                    b.Navigation("CategoriaFinanceira");

                    b.Navigation("CentroCusto");

                    b.Navigation("Clinica");

                    b.Navigation("CriadoPor");

                    b.Navigation("Internacao");

                    b.Navigation("SolicitacaoExame");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Tutor", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Agendamento", b =>
                {
                    b.Navigation("Prontuario");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.CentroCusto", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("CentrosCusto");

                    b.Navigation("ClinicaUsuarios");

                    b.Navigation("Pacientes");

                    b.Navigation("Produtos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Internacao", b =>
                {
                    b.Navigation("Evolucoes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Internacoes");

                    b.Navigation("Prontuarios");

                    b.Navigation("SolicitacoesExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensPedido");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("Prescricoes");

                    b.Navigation("SolicitacoesExame");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.SolicitacaoExame", b =>
                {
                    b.Navigation("Resultado");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.TransacaoFinanceira", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.UnidadeProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AgendamentosComoVet");

                    b.Navigation("ClinicaUsuarios");

                    b.Navigation("LogsAuditoria");

                    b.Navigation("MovimentacoesAprovadas");

                    b.Navigation("MovimentacoesCriadas");

                    b.Navigation("PedidosAprovados");

                    b.Navigation("PedidosCriados");

                    b.Navigation("Prontuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
